"""Initial migration

Revision ID: 5545340501ee
Revises: 
Create Date: 2020-07-27 12:17:46.311655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5545340501ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('op')
    # ### end Alembic commands ###
